# Default values for appsbroker_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vpc:
  autoCreateSubnetworks: false

subnet:
  create:
    mgmt:
      ip_range: 10.2.0.0/20
      region: europe-west2
    private:
      ip_range: 10.2.16.0/20
      region: europe-west2

cloudrun:
  image: gcr.io/cloudrun/hello
  region: europe-west2

cloudfunc:
  region: europe-west2
  runtime: nodejs8
  sourceArchiveUrl: gs://config-connector-samples/cloudfunctionsfunction/http_trigger.zip