apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: {{ .Release.Name }}
spec:
  googleServiceAccount: "{{ .Release.Name }}@config-connector-main.iam.gserviceaccount.com"