apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: ab-{{ .Release.Name }}-{{ .Values.project.environment }}
spec:
  googleServiceAccount: "ab-{{ .Release.Name }}-{{ .Values.project.environment }}@{{ .Values.mgmtAccount }}.iam.gserviceaccount.com"