{{ if .Values.iam.viewer }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}-viewers
  namespace: {{ .Values.mgmtAccount }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}
  bindings:
    - role: roles/viewer
      members:
      {{- range $.Values.iam.viewer }}
        - member: {{ . }}
      {{- end }}
{{ end }}