apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/organization-id: {{ .Values.project.organizationID | quote }}
    cnrm.cloud.google.com/auto-create-network: "false"
  labels:
    customer: {{ .Values.project.customer | quote }}
    project_name: {{ .Values.project.name | quote }}
    environment: {{ .Values.project.environment | quote }}

  name: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}
  namespace: resource-manager
spec:
  name: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}
  folderRef:
    external: {{ .Values.project.parentFolderID | quote }}
  billingAccountRef:
    external: {{ .Values.project.billingAccountID | quote }}