apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/organization-id: {{ .Values.project.organizationID | quote }}
    cnrm.cloud.google.com/auto-create-network: "false"
  labels:
    customer: {{ .Values.project.customer | quote }}
    project_name: {{ .Values.project.name | quote }}
    environment: {{ .Values.project.environment | quote }}

  name: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}
  namespace: {{ .Values.mgmtAccount }}
spec:
  name: {{ .Values.project.customer }}-{{ .Values.project.name }}-{{ .Values.project.environment }}
  folderRef:
    external: {{ .Values.project.parentFolderID | quote }}
  billingAccountRef:
    external: {{ .Values.project.billingAccountID | quote }}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: resourcemanagerpolicy-sample-project
spec:
  projectRef:
    name: resourcemanagerpolicy-dep-project
  constraint: "constraints/compute.skipDefaultNetworkCreation"
  booleanPolicy:
    enforced: true