apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ .Release.Name }}-policy
  namespace: resource-manager
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ .Release.Name }}
  bindings:
    - members:
        - serviceAccount:svc-{{ .Values.mgmgAccount }}@{{ .Values.mgmgAccount }}.iam.gserviceaccount.com
      role: roles/owner
    - members:
        - serviceAccount:{{ .Release.Name }}@{{ .Values.mgmgAccount }}.iam.gserviceaccount.com
      role: roles/storage.admin
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Release.Name }}
  name: {{ .Release.Name }}-sa
  namespace: resource-manager