apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ .Release.Name }}-sa-project
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: {{ .Release.Name }}
    namespace: config-connector-mgmt
  bindings:
    - members:
        - serviceAccount:svc-config-connector-main@config-connector-main.iam.gserviceaccount.com
      role: roles/owner
    - members:
        - serviceAccount:{{ .Release.Name }}@{{ .Release.Name }}.iam.gserviceaccount.com
      role: roles/storage.admin
  auditConfigs:
    - service: allServices
      auditLogConfigs:
        - logType: DATA_WRITE
        - logType: DATA_READ
          exemptedMembers:
            - serviceAccount:{{ .Release.Name }}@{{ .Release.Name }}.iam.gserviceaccount.com
    - service: compute.googleapis.com
      auditLogConfigs:
        - logType: ADMIN_READ
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: config-connector-mgmt