{{ if .Values.subnet.create }}
{{- range $k, $v := .Values.subnet.create }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    environment: {{ $.Values.project.environment | quote }}
  name: {{ $.Values.project.name }}-{{ $k }}-subnet
  namespace: {{ $.Values.project.customer }}-{{ $.Values.project.name }}-{{ $.Values.project.environment }}
spec:
  ipCidrRange: {{ $v.cidr_range }}
  region: {{ $v.region }}
  description: {{ $k }} Subnetwork via Config Connector
  privateIpGoogleAccess: false
  networkRef:
    name: {{ $.Values.project.name }}-network
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
---
{{- end }}
{{- end }}