apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: {{ .Release.Name }}-network
  namespace: {{ .Release.Name }}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false