apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: {{ .Release.Name }}-network
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: {{ .Values.vpc.autoCreateSubnetworks }}