# Default values for appsbroker-project-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mgmtAccount:

project:
  parentFolderID:
  billingAccountID:
  organizationID:
  environment:

subnet:
  create:
    private:
      ip_range: 192.168.0.0/20
      region: europe-west2