apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computeinstance-{{ .Release.Name }}-1-cloudmachine
spec:
  description: a sample encrypted, blank disk
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: {{ .Values.compute.zone }}
  diskEncryptionKey:
    rawKey:
      valueFrom:
        secretKeyRef:
          name: computeinstance-{{ .Release.Name }}-cloudmachine
          key: diskEncryptionKey
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computeinstance-{{ .Release.Name }}-2-cloudmachine
spec:
  size: 1
  type: pd-ssd
  location: {{ .Values.compute.zone }}