apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
  name: computeinstance-{{ .Release.Name }}-cloudmachine
  labels:
    created-from: "image"
    network-type: "subnetwork"
spec:
  machineType: {{ .Values.compute.machineType }}
  zone: {{ .Values.compute.zone }}
  bootDisk:
    initializeParams:
      size: 24
      type: pd-ssd
      sourceImageRef:
        external: debian-cloud/debian-9
  networkInterface:
    - subnetworkRef:
        name: computeinstance-{{ .Release.Name }}-cloudmachine
      aliasIpRange:
        - ipCidrRange: /24
          subnetworkRangeName: cloudrange
  attachedDisk:
    - sourceDiskRef:
        name: computeinstance-{{ .Release.Name }}-1-cloudmachine
      mode: READ_ONLY
      deviceName: proxycontroldisk
      diskEncryptionKeyRaw:
        valueFrom:
          secretKeyRef:
            name: computeinstance-{{ .Release.Name }}-cloudmachine
            key: diskEncryptionKey
    - sourceDiskRef:
        name: computeinstance-{{ .Release.Name }}-2-cloudmachine
      mode: READ_WRITE
      deviceName: persistentdisk
  minCpuPlatform: "Intel Skylake"
  serviceAccount:
    serviceAccountRef:
      name: inst-{{ .Release.Name }}-cloudmachine
    scopes:
    - compute-rw
    - logging-write