apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: {{ $.Release.Name }}-sample
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: {{ .Values.cloudrun.region | quote }}
  projectRef:
    external: projects/{{ .Release.Namespace }}
  template:
    containers:
      - env:
          - name: "FOO"
            value: "bar]"
        image: {{ .Values.cloudrun.image | quote }}
    scaling:
      maxInstanceCount: 2
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"