apiVersion: cloudfunctions.cnrm.cloud.google.com/v1beta1
kind: CloudFunctionsFunction
metadata:
  name: {{ .Release.Name }}-sample-httpstrigger
spec:
  projectRef:
    external: "projects/{{ .Release.Namespace }}"
  region: {{ .Values.cloudfunc.region | quote }}
  runtime: {{ .Values.cloudfunc.runtime | quote }}
  sourceArchiveUrl: {{ .Values.cloudfunc.sourceArchiveUrl | quote }}
  entryPoint: "helloGET"
  httpsTrigger:
    securityLevel: "SECURE_OPTIONAL"